drive_controller:
  ros__parameters:
    points:
      - [0.859, -2.330, 0.001,   # x,y,yaw; 
         0.529, 0.045, 0.001,
         1.765, 0.003, 0.001,]  # x,y,yaw; 
    point_zones: 
      - ["None", "C", "None"]           # keepout_zone
    gripper_cmds: 
      - ["catch", "perevorot1", "start_state"]
    gripper_cmds2: 
      - ["up", "release", ""]
    
    gripper_serial:
      device: "/dev/ttyAMA2"
      baudrate: 115200
    
    time_until_end: 95