drive_controller:
  ros__parameters:
    points:
      - [1.1211, -0.34499, 1.5210959,   # x,y,yaw; орехи 1
         0.859, -0.340065, 1.5210959,   # x,y,yaw; зона выгрузки 1
         1.765, 0.003, 0.001,]  # x,y,yaw; гнездо
    point_zones: 
      - ["None", "C", "None"]           # keepout_zone
    gripper_cmds: 
      - ["catch", "perevorot1", "start_state"]
    gripper_cmds2: 
      - ["up", "release", ""]
    
    gripper_serial:
      device: "/dev/ttyAMA2"
      baudrate: 115200
    
    time_until_end: 95